console.log('1234'.replace(/\d/g, 'X'))
console.log('1234'.replace(/\d*/g, 'X'))
console.log('1234'.replace(/\d*?/g, 'X'))
console.log('1234'.replace(/\d+?/g, 'X'))
console.log('1234'.replace(/\d??/g, 'X'))